name: Force Push and Direct Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.auto_merge_enabled == true
    
    steps:
      - name: Auto-merge PR
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            await github.rest.pulls.merge({
              owner,
              repo,
              pull_number: number,
              merge_method: 'squash',
              commit_title: `Merge PR #${number}`,
              commit_message: 'Auto-merged by GitHub Actions'
            });

  force-push-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - name: Check force push
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, before, after } = context.payload;
            console.log(`Force push detected: ${before} -> ${after}`);
            // Log force push for audit purposes
            await github.rest.issues.create({
              owner,
              repo,
              title: `Force Push Detected: ${before.substring(0, 7)} -> ${after.substring(0, 7)}`,
              body: `Force push detected on main branch.\n\n**Before:** ${before}\n**After:** ${after}\n\nThis is allowed for development purposes.`
            });
